---
label: Services
hide_body: false
fields:
- name: service_header
  type: text
  config:
    required: false
  label: Service Header
- name: service_subheader
  type: text
  config:
    required: false
  label: Service Subheader
- name: service_image
  type: file
  config:
    maxSize: 250
  label: Service Image
- name: service_item
  type: field_group_list
  fields:
  - name: service_item_name
    type: text
    config:
      required: false
    label: Service Item Name
  - name: service_item_description
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Service Item Description
  - name: service_item_icon
    type: file
    config:
      maxSize: 250
    label: Service Item Icon
  config:
    min: 
    max: 
    labelField: 
  label: Service Items
